/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * DeleteV1ImageProjectsIdResponse401MessageEnum
 */
export type DeleteV1ImageProjectsIdResponse401MessageEnum = "Unauthorized";

/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$DeleteV1ImageProjectsIdResponse401MessageEnum =
  "Unauthorized";
