/**
 * Generated by Sideko (sideko.dev)
 **/
/**
 * DeleteV1VideoProjectsIdResponse401MessageEnum
 */
export type DeleteV1VideoProjectsIdResponse401MessageEnum = "Unauthorized";
/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$DeleteV1VideoProjectsIdResponse401MessageEnum = "Unauthorized";
