/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

/**
 * The request is not properly authenticated
 */
export type DeleteV1ImageProjectsIdResponse401 = {
  message: types.DeleteV1ImageProjectsIdResponse401MessageEnum;
};
