/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

/**
 * Requested resource is not found
 */
export type DeleteV1ImageProjectsIdResponse404 = {
  message: types.DeleteV1ImageProjectsIdResponse404MessageEnum;
};
