/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * DeleteV1VideoProjectsIdResponse404MessageEnum
 */
export type DeleteV1VideoProjectsIdResponse404MessageEnum = "Not Found";

/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$DeleteV1VideoProjectsIdResponse404MessageEnum =
  "Not Found";
