/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

/**
 * The request is not properly authenticated
 */
export type DeleteV1VideoProjectsIdResponse401 = {
  message: types.DeleteV1VideoProjectsIdResponse401MessageEnum;
};
