/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * The status of the video.
 */
export enum GetV1VideoProjectsIdResponseStatusEnum {
  Canceled = "canceled",
  Complete = "complete",
  Draft = "draft",
  Error = "error",
  Queued = "queued",
  Rendering = "rendering",
}
