/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * In the case of an error, this object will contain the error encountered during video render
 */
export type GetV1ImageProjectsIdResponseError = {
  /**
   * An error code to indicate why a failure happened.
   */
  code: string;
  /**
   * Details on the reason why a failure happened.
   */
  message: string;
};
