/**
 * Generated by Sideko (sideko.dev)
 **/
/**
 * GetV1VideoProjectsIdResponse401MessageEnum
 */
export type GetV1VideoProjectsIdResponse401MessageEnum = "Unauthorized";
/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$GetV1VideoProjectsIdResponse401MessageEnum = "Unauthorized";
