/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * The status of the image.
 */
export enum GetV1ImageProjectsIdResponseStatusEnum {
  Canceled = "canceled",
  Complete = "complete",
  Draft = "draft",
  Error = "error",
  Queued = "queued",
  Rendering = "rendering",
}
