/**
 * Generated by Sideko (sideko.dev)
 **/

export enum GetV1ImageProjectsIdResponseStatusEnum {
  Canceled = "canceled",
  Complete = "complete",
  Draft = "draft",
  Error = "error",
  Queued = "queued",
  Rendering = "rendering",
}
