/**
 * Generated by Sideko (sideko.dev)
 **/

export enum GetV1VideoProjectsIdResponseTypeEnum {
  Animation = "ANIMATION",
  FaceSwap = "FACE_SWAP",
  ImageToVideo = "IMAGE_TO_VIDEO",
  LipSync = "LIP_SYNC",
  TextToVideo = "TEXT_TO_VIDEO",
  VideoToVideo = "VIDEO_TO_VIDEO",
}
