/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * GetV1VideoProjectsIdResponseTypeEnum
 */
export type GetV1VideoProjectsIdResponseTypeEnum =
  | "ANIMATION"
  | "FACE_SWAP"
  | "IMAGE_TO_VIDEO"
  | "LIP_SYNC"
  | "TEXT_TO_VIDEO"
  | "VIDEO_TO_VIDEO";

/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$GetV1VideoProjectsIdResponseTypeEnum =
  | "ANIMATION"
  | "FACE_SWAP"
  | "IMAGE_TO_VIDEO"
  | "LIP_SYNC"
  | "TEXT_TO_VIDEO"
  | "VIDEO_TO_VIDEO";
