/**
 * Generated by Sideko (sideko.dev)
 **/

export enum GetV1ImageProjectsIdResponseTypeEnum {
  AiHeadshot = "AI_HEADSHOT",
  AiImage = "AI_IMAGE",
  FaceSwap = "FACE_SWAP",
  ImageUpscaler = "IMAGE_UPSCALER",
  QrCode = "QR_CODE",
}
