/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * GetV1ImageProjectsIdResponseTypeEnum
 */
export enum GetV1ImageProjectsIdResponseTypeEnum {
  AiHeadshot = "AI_HEADSHOT",
  AiImage = "AI_IMAGE",
  FaceSwap = "FACE_SWAP",
  ImageUpscaler = "IMAGE_UPSCALER",
  PhotoEditor = "PHOTO_EDITOR",
  QrCode = "QR_CODE",
}
