/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * The status of the video.
 */
export type GetV1VideoProjectsIdResponseStatusEnum =
  | "canceled"
  | "complete"
  | "draft"
  | "error"
  | "queued"
  | "rendering";

/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$GetV1VideoProjectsIdResponseStatusEnum =
  | "canceled"
  | "complete"
  | "draft"
  | "error"
  | "queued"
  | "rendering";
