/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * GetV1ImageProjectsIdResponse401MessageEnum
 */
export type GetV1ImageProjectsIdResponse401MessageEnum = "Unauthorized";

/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$GetV1ImageProjectsIdResponse401MessageEnum =
  "Unauthorized";
