/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * The download url and expiration date of the image project
 */
export type GetV1ImageProjectsIdResponseDownloadsItem = {
  expires_at: string;
  url: string;
};
