/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * GetV1ImageProjectsIdResponseTypeEnum
 */
export type GetV1ImageProjectsIdResponseTypeEnum =
  | "AI_HEADSHOT"
  | "AI_IMAGE"
  | "BACKGROUND_REMOVER"
  | "FACE_SWAP"
  | "IMAGE_UPSCALER"
  | "PHOTO_EDITOR"
  | "QR_CODE";

/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$GetV1ImageProjectsIdResponseTypeEnum =
  | "AI_HEADSHOT"
  | "AI_IMAGE"
  | "BACKGROUND_REMOVER"
  | "FACE_SWAP"
  | "IMAGE_UPSCALER"
  | "PHOTO_EDITOR"
  | "QR_CODE";
