/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * GetV1VideoProjectsIdResponse404MessageEnum
 */
export type GetV1VideoProjectsIdResponse404MessageEnum = "Not Found";

/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$GetV1VideoProjectsIdResponse404MessageEnum = "Not Found";
