/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

/**
 * Requested resource is not found
 */
export type GetV1VideoProjectsIdResponse404 = {
  message: types.GetV1VideoProjectsIdResponse404MessageEnum;
};
