/**
 * Generated by Sideko (sideko.dev)
 **/
/**
 * GetV1ImageProjectsIdResponse404MessageEnum
 */
export type GetV1ImageProjectsIdResponse404MessageEnum = "Not Found";
/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$GetV1ImageProjectsIdResponse404MessageEnum = "Not Found";
