/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * The download url and expiration date of the video project
 */
export type GetV1VideoProjectsIdResponseDownload = {
  expires_at: string;
  url: string;
};
