/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * PostV1FilesUploadUrlsResponse404MessageEnum
 */
export type PostV1FilesUploadUrlsResponse404MessageEnum = "Not Found";

/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1FilesUploadUrlsResponse404MessageEnum = "Not Found";
