/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * PostV1AiImageGeneratorBodyOrientationEnum
 */
export enum PostV1AiImageGeneratorBodyOrientationEnum {
  Landscape = "landscape",
  Portrait = "portrait",
  Square = "square",
}
