/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * PostV1AiImageGeneratorBodyStyle
 */
export type PostV1AiImageGeneratorBodyStyle = {
  /**
   * The prompt used for the image.
   */
  prompt: string;
};
