/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

/**
 * PostV1FaceSwapPhotoBody
 */
export type PostV1FaceSwapPhotoBody = {
  /**
   * Provide the assets for face swap photo
   */
  assets: types.PostV1FaceSwapPhotoBodyAssets;
  /**
   * The name of image
   */
  name?: string;
};
