/**
 * Generated by Sideko (sideko.dev)
 **/

export type PostV1LipSyncResponse = {
  /**
   * Estimated cost of the video in terms of number of frames needed to render the video. Frames will be adjusted when the video completes
   */
  estimated_frame_cost: number;
  /**
   * Unique ID of the video. This value can be used in the [get video project API](#tag/video-projects/get/v1/video-projects/{id}) to fetch additional details such as status
   */
  id: string;
};
