/**
 * Generated by Sideko (sideko.dev)
 **/

export type PostV1FaceSwapPhotoBodyAssets = {
  /**
   * This is the image from which the face is extracted. This is the &#x60;file_path&#x60; field from the response of the [upload urls API](/docs/api/tag/files/post/v1/files/upload-urls)
   */
  source_file_path: string;
  /**
   * This is the image where the face from the source image will be placed. This is the &#x60;file_path&#x60; field from the response of the [upload urls API](/docs/api/tag/files/post/v1/files/upload-urls)
   */
  target_file_path: string;
};
