/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Determines whether the resulting video will have the same frame per second as the original video, or half.
 * * `FULL` - the result video will have the same FPS as the input video
 * * `HALF` - the result video will have half the FPS as the input video
 */
export enum PostV1VideoToVideoBodyFpsResolutionEnum {
  Full = "FULL",
  Half = "HALF",
}
