/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

/**
 * PostV1AiImageUpscalerBodyStyle
 */
export type PostV1AiImageUpscalerBodyStyle = {
  enhancement: types.PostV1AiImageUpscalerBodyStyleEnhancementEnum;
  /**
   * A prompt to guide the final image. This value is ignored if `enhancement` is not Creative
   */
  prompt?: string;
};
