/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * PostV1AiImageUpscalerBodyStyleEnhancementEnum
 */
export enum PostV1AiImageUpscalerBodyStyleEnhancementEnum {
  Balanced = "Balanced",
  Creative = "Creative",
  Resemblance = "Resemblance",
}
