/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

export type PostV1VideoToVideoBodyAssets = {
  /**
   * The path of the input video. This is the &#x60;file_path&#x60; field from the response of the [upload urls API](/docs/api/tag/files/post/v1/files/upload-urls). This field is required if &#x60;video_source&#x60; is &#x60;file&#x60;
   */
  video_file_path?: string;
  video_source: types.PostV1VideoToVideoBodyAssetsVideoSourceEnum;
  /**
   * Using a youtube video as the input source. This field is required if &#x60;video_source&#x60; is &#x60;youtube&#x60;
   */
  youtube_url?: string;
};
