/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

export type PostV1AiHeadshotGeneratorResponse404 = {
  message: types.PostV1AiHeadshotGeneratorResponse404MessageEnum;
};
