/**
 * Generated by Sideko (sideko.dev)
 **/
/**
 * The type of asset to upload
 */
export type PostV1FilesUploadUrlsBodyItemsItemTypeEnum = "audio" | "image" | "video";
/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1FilesUploadUrlsBodyItemsItemTypeEnum = "audio" | "image" | "video";
