/**
 * Generated by Sideko (sideko.dev)
 **/

export type PostV1FaceSwapPhotoResponse = {
  frame_cost: number;
  /**
   * Unique ID of the video. This value can be used in the [get video project API](#tag/video-projects/get/v1/video-projects/{id}) to fetch additional details such as status
   */
  id: string;
};
