/**
 * Generated by Sideko (sideko.dev)
 **/
/**
 * PostV1AiImageGeneratorBodyOrientationEnum
 */
export type PostV1AiImageGeneratorBodyOrientationEnum = "landscape" | "portrait" | "square";
/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1AiImageGeneratorBodyOrientationEnum = "landscape" | "portrait" | "square";
