/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Optionally add an audio source if you'd like to incorporate audio into your video
 */
export enum PostV1AnimationBodyAssetsAudioSourceEnum {
  File = "file",
  None = "none",
  Youtube = "youtube",
}
