/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * The type of asset to upload
 */
export enum PostV1FilesUploadUrlsBodyItemsItemTypeEnum {
  Audio = "audio",
  Image = "image",
  Video = "video",
}
