/**
 * Generated by Sideko (sideko.dev)
 **/
/**
 * PostV1FaceSwapBodyAssetsVideoSourceEnum
 */
export type PostV1FaceSwapBodyAssetsVideoSourceEnum = "file" | "youtube";
/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1FaceSwapBodyAssetsVideoSourceEnum = "file" | "youtube";
