/**
 * Generated by Sideko (sideko.dev)
 **/

export type PostV1AiQrCodeGeneratorBodyStyle = {
  /**
   * To use our templates, pass in one of Watercolor, Cyberpunk City, Ink Landscape, Interior Painting, Japanese Street, Mech, Minecraft, Picasso Painting, Game Map, Spaceship, Chinese Painting, Winter Village, or pass any custom art style.
   */
  art_style: string;
};
