/**
 * Generated by Sideko (sideko.dev)
 **/
/**
 * PostV1FaceSwapResponse401MessageEnum
 */
export type PostV1FaceSwapResponse401MessageEnum = "Unauthorized";
/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1FaceSwapResponse401MessageEnum = "Unauthorized";
