/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * PostV1FilesUploadUrlsResponse401MessageEnum
 */
export type PostV1FilesUploadUrlsResponse401MessageEnum = "Unauthorized";

/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1FilesUploadUrlsResponse401MessageEnum =
  "Unauthorized";
