/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Determines the orientation of the output video
 */
export enum PostV1TextToVideoBodyOrientationEnum {
  Landscape = "landscape",
  Portrait = "portrait",
  Square = "square",
}
