/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * PostV1AiQrCodeGeneratorResponse404MessageEnum
 */
export type PostV1AiQrCodeGeneratorResponse404MessageEnum = "Not Found";

/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1AiQrCodeGeneratorResponse404MessageEnum =
  "Not Found";
