/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

export type PostV1TextToVideoBody = {
  /**
   * The total duration of the output video in seconds.
   */
  end_seconds: number;
  /**
   * The name of video
   */
  name?: string;
  /**
   * Determines the orientation of the output video
   */
  orientation: types.PostV1TextToVideoBodyOrientationEnum;
  style: types.PostV1TextToVideoBodyStyle;
};
