/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * PostV1FilesUploadUrlsResponseItemsItem
 */
export type PostV1FilesUploadUrlsResponseItemsItem = {
  expires_at: string;
  file_path: string;
  upload_url: string;
};
