/**
 * Generated by Sideko (sideko.dev)
 **/
/**
 * PostV1LipSyncBodyAssetsVideoSourceEnum
 */
export type PostV1LipSyncBodyAssetsVideoSourceEnum = "file" | "youtube";
/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1LipSyncBodyAssetsVideoSourceEnum = "file" | "youtube";
