/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Determines the orientation of the output video
 */
export type PostV1TextToVideoBodyOrientationEnum =
  | "landscape"
  | "portrait"
  | "square";

/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1TextToVideoBodyOrientationEnum =
  | "landscape"
  | "portrait"
  | "square";
