/**
 * Generated by Sideko (sideko.dev)
 **/

export enum PostV1VideoToVideoBodyStyleModelEnum {
  AbsoluteReality = "Absolute Reality",
  Dreamshaper = "Dreamshaper",
  Flat2dAnime = "Flat 2D Anime",
  Default = "default",
}
