/**
 * Generated by Sideko (sideko.dev)
 **/
/**
 * PostV1VideoToVideoBodyAssetsVideoSourceEnum
 */
export type PostV1VideoToVideoBodyAssetsVideoSourceEnum = "file" | "youtube";
/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1VideoToVideoBodyAssetsVideoSourceEnum = "file" | "youtube";
