/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Provide the assets for headshot photo
 */
export type PostV1AiHeadshotGeneratorBodyAssets = {
  /**
   * The image used to generate the headshot. This image must contain one detectable face. This is the `file_path` field from the response of the [upload urls API](/docs/api/tag/files/post/v1/files/upload-urls)
   */
  image_file_path: string;
};
