/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

export type PostV1AiHeadshotGeneratorBody = {
  /**
   * Provide the assets for headshot photo
   */
  assets: types.PostV1AiHeadshotGeneratorBodyAssets;
  /**
   * The name of image
   */
  name?: string;
};
