/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

/**
 * PostV1FilesUploadUrlsBody
 */
export type PostV1FilesUploadUrlsBody = {
  items: types.PostV1FilesUploadUrlsBodyItemsItem[];
};
