/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

export type PostV1AiQrCodeGeneratorResponse404 = {
  message: types.PostV1AiQrCodeGeneratorResponse404MessageEnum;
};
