/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

/**
 * PostV1AiQrCodeGeneratorBody
 */
export type PostV1AiQrCodeGeneratorBody = {
  /**
   * The content of the QR code.
   */
  content: string;
  /**
   * The name of image
   */
  name?: string;
  style: types.PostV1AiQrCodeGeneratorBodyStyle;
};
