/**
 * Generated by Sideko (sideko.dev)
 **/

export type PostV1AiImageUpscalerBodyAssets = {
  /**
   * The image to upscale. This is the &#x60;file_path&#x60; field from the response of the [upload urls API](/docs/api/tag/files/post/v1/files/upload-urls)
   */
  image_file_path: string;
};
