/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

export type PostV1AiImageUpscalerBodyStyle = {
  enhancement: types.PostV1AiImageUpscalerBodyStyleEnhancementEnum;
  /**
   * A prompt to guide the final image. This value is ignored if &#x60;enhancement&#x60; is not Creative
   */
  prompt?: string;
};
