/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

export type PostV1AiHeadshotGeneratorResponse401 = {
  message: types.PostV1AiHeadshotGeneratorResponse401MessageEnum;
};
