/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

export type PostV1FilesUploadUrlsBodyItemsItem = {
  /**
   * the extension of the file to upload. Do not include the dot (.) before the extension.
   */
  extension: string;
  /**
   * The type of asset to upload
   */
  type: types.PostV1FilesUploadUrlsBodyItemsItemTypeEnum;
};
