/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * PostV1TextToVideoResponse401MessageEnum
 */
export type PostV1TextToVideoResponse401MessageEnum = "Unauthorized";

/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1TextToVideoResponse401MessageEnum = "Unauthorized";
