/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

/**
 * PostV1AiImageUpscalerBody
 */
export type PostV1AiImageUpscalerBody = {
  /**
   * Provide the assets for upscaling
   */
  assets: types.PostV1AiImageUpscalerBodyAssets;
  /**
   * The name of image
   */
  name?: string;
  scale_factor: number;
  style: types.PostV1AiImageUpscalerBodyStyle;
};
