/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

/**
 * Success
 */
export type PostV1FilesUploadUrlsResponse = {
  items: types.PostV1FilesUploadUrlsResponseItemsItem[];
};
