/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

/**
 * Provide the assets for animation.
 */
export type PostV1AnimationBodyAssets = {
  /**
   * The path of the input audio. This is the `file_path` field from the response of the [upload urls API](/docs/api/tag/files/post/v1/files/upload-urls). This field is required if `audio_source` is `file`
   */
  audio_file_path?: string;
  /**
   * Optionally add an audio source if you'd like to incorporate audio into your video
   */
  audio_source: types.PostV1AnimationBodyAssetsAudioSourceEnum;
  /**
   * An initial image to use a the first frame of the video. This is the `file_path` field from the response of the [upload urls API](/docs/api/tag/files/post/v1/files/upload-urls)
   */
  image_file_path?: string;
  /**
   * Using a youtube video as the input source. This field is required if `audio_source` is `youtube`
   */
  youtube_url?: string;
};
