/**
 * Generated by Sideko (sideko.dev)
 **/
/**
 * PostV1LipSyncResponse404MessageEnum
 */
export type PostV1LipSyncResponse404MessageEnum = "Not Found";
/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1LipSyncResponse404MessageEnum = "Not Found";
