/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * Optionally add an audio source if you'd like to incorporate audio into your video
 */
export type PostV1AnimationBodyAssetsAudioSourceEnum =
  | "file"
  | "none"
  | "youtube";

/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1AnimationBodyAssetsAudioSourceEnum =
  | "file"
  | "none"
  | "youtube";
