/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * PostV1VideoToVideoBodyAssetsVideoSourceEnum
 */
export enum PostV1VideoToVideoBodyAssetsVideoSourceEnum {
  File = "file",
  Youtube = "youtube",
}
