/**
 * Generated by Sideko (sideko.dev)
 **/
/**
 * PostV1AiImageUpscalerBodyStyleEnhancementEnum
 */
export type PostV1AiImageUpscalerBodyStyleEnhancementEnum = "Balanced" | "Creative" | "Resemblance";
/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1AiImageUpscalerBodyStyleEnhancementEnum = "Balanced" | "Creative" | "Resemblance";
