/**
 * Generated by Sideko (sideko.dev)
 **/
/**
 * PostV1AiPhotoEditorResponse404MessageEnum
 */
export type PostV1AiPhotoEditorResponse404MessageEnum = "Not Found";
/**
 * @internal
 * Denotes external values of enum (same as above) to stay consistent with other types
 */
export type External$PostV1AiPhotoEditorResponse404MessageEnum = "Not Found";
