/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * PostV1AiHeadshotGeneratorResponse401MessageEnum
 */
export enum PostV1AiHeadshotGeneratorResponse401MessageEnum {
  Unauthorized = "Unauthorized",
}
