/**
 * Generated by Sideko (sideko.dev)
 **/

import { types } from "magic-hour";

export type PostV1AiQrCodeGeneratorResponse401 = {
  message: types.PostV1AiQrCodeGeneratorResponse401MessageEnum;
};
