/**
 * Generated by Sideko (sideko.dev)
 **/

export type PostV1AiQrCodeGeneratorResponse = {
  frame_cost: number;
  /**
   * Unique ID of the image. This value can be used in the [get image project API](/api/tag/image-projects/get/v1/image-projects/{id}) to fetch additional details such as status
   */
  id: string;
};
