/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * PostV1ImageToVideoBodyStyle
 */
export type PostV1ImageToVideoBodyStyle = {
  /**
   * The prompt used for the video.
   */
  prompt?: string | null;
};
