/**
 * Generated by Sideko (sideko.dev)
 **/

import {
  External$PostV1AiHeadshotGeneratorResponse401MessageEnum,
  PostV1AiHeadshotGeneratorResponse401MessageEnum,
} from "./post-v1-ai-headshot-generator-response401-message-enum";
import { zodTransform } from "magic-hour/core";
import * as z from "zod";

/**
 * The request is not properly authenticated
 */
export type PostV1AiHeadshotGeneratorResponse401 = {
  message: PostV1AiHeadshotGeneratorResponse401MessageEnum;
};

/**
 * @internal
 * PostV1AiHeadshotGeneratorResponse401 without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$PostV1AiHeadshotGeneratorResponse401 = {
  message: External$PostV1AiHeadshotGeneratorResponse401MessageEnum;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object PostV1AiHeadshotGeneratorResponse401
 */
const SchemaIn$PostV1AiHeadshotGeneratorResponse401: z.ZodType<
  PostV1AiHeadshotGeneratorResponse401, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    message: z.enum(["Unauthorized"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      message: "message",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$PostV1AiHeadshotGeneratorResponse401
 */
const SchemaOut$PostV1AiHeadshotGeneratorResponse401: z.ZodType<
  External$PostV1AiHeadshotGeneratorResponse401, // output type of this zod object
  z.ZodTypeDef,
  PostV1AiHeadshotGeneratorResponse401 // the object to be transformed
> = z
  .object({
    message: z.enum(["Unauthorized"]),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      message: "message",
    });
  });

export const Schemas$PostV1AiHeadshotGeneratorResponse401 = {
  in: SchemaIn$PostV1AiHeadshotGeneratorResponse401,
  out: SchemaOut$PostV1AiHeadshotGeneratorResponse401,
};
