/**
 * Generated by Sideko (sideko.dev)
 **/

/**
 * * `v1` - more detail, closer prompt adherence, and frame-by-frame previews.
 * * `v2` - faster, more consistent, and less noisy.
 * * `default` - use the default version for the selected art style.
 */
export enum PostV1VideoToVideoBodyStyleVersionEnum {
  Default = "default",
  V1 = "v1",
  V2 = "v2",
}
