/**
 * Language to translate the video's speech into.
 */
export type V1AiVideoTranslatorCreateBodyTargetLanguageEnum =
  | "Afrikaans"
  | "Arabic"
  | "Bengali"
  | "Bulgarian"
  | "Catalan"
  | "Chinese (Simplified)"
  | "Chinese (Traditional)"
  | "Croatian"
  | "Czech"
  | "Danish"
  | "Dutch"
  | "English"
  | "Estonian"
  | "Finnish"
  | "French"
  | "German"
  | "Greek"
  | "Gujarati"
  | "Hebrew"
  | "Hindi"
  | "Hungarian"
  | "Indonesian"
  | "Italian"
  | "Japanese"
  | "Kannada"
  | "Kazakh"
  | "Korean"
  | "Latvian"
  | "Lithuanian"
  | "Malay"
  | "Malayalam"
  | "Marathi"
  | "Norwegian"
  | "Persian"
  | "Polish"
  | "Portuguese"
  | "Punjabi"
  | "Romanian"
  | "Russian"
  | "Serbian"
  | "Slovak"
  | "Slovenian"
  | "Spanish"
  | "Swahili"
  | "Swedish"
  | "Tamil"
  | "Telugu"
  | "Thai"
  | "Turkish"
  | "Ukrainian"
  | "Urdu"
  | "Vietnamese"
  | "Welsh";
