/**
 * V1VideoToVideoCreateBodyStyleArtStyleEnum
 */
export type V1VideoToVideoCreateBodyStyleArtStyleEnum =
  | "3D Render"
  | "Airbender"
  | "Android"
  | "Anime Warrior"
  | "Armored Knight"
  | "Assassin's Creed"
  | "Avatar"
  | "Black Spiderman"
  | "Boba Fett"
  | "Celestial Skin"
  | "Chinese Swordsmen"
  | "Clay"
  | "Comic"
  | "Cyberpunk"
  | "Cypher"
  | "Dark Fantasy"
  | "Dragonball Z"
  | "Future Bot"
  | "Futuristic Fantasy"
  | "GTA"
  | "Ghost"
  | "Gundam"
  | "Hologram"
  | "Illustration"
  | "Impressionism"
  | "Ink"
  | "Ink Poster"
  | "Jinx"
  | "Knight"
  | "Lego"
  | "Link"
  | "Marble"
  | "Mario"
  | "Master Chief"
  | "Mech"
  | "Minecraft"
  | "Mystique"
  | "Naruto"
  | "Neon Dream"
  | "No Art Style"
  | "Oil Painting"
  | "On Fire"
  | "Origami"
  | "Pixar"
  | "Pixel"
  | "Power Armor"
  | "Power Ranger"
  | "Retro Anime"
  | "Retro Sci-Fi"
  | "Samurai"
  | "Samurai Bot"
  | "Solid Snake"
  | "Spartan"
  | "Starfield"
  | "Street Fighter"
  | "Studio Ghibli"
  | "Sub-Zero"
  | "The Void"
  | "Tomb Raider"
  | "Underwater"
  | "Van Gogh"
  | "Viking"
  | "Watercolor"
  | "Wu Kong"
  | "Zelda";
