/**
 * Generated by Sideko (sideko.dev)
 **/

import { CoreClient, CoreResourceClient } from "magic-hour/core";
import { AiImageGeneratorClient } from "magic-hour/resources/v1/ai-image-generator";
import { FaceSwapClient } from "magic-hour/resources/v1/face-swap";
import { FaceSwapPhotoClient } from "magic-hour/resources/v1/face-swap-photo";
import { FilesClient } from "magic-hour/resources/v1/files";
import { ImageProjectsClient } from "magic-hour/resources/v1/image-projects";
import { ImageToVideoClient } from "magic-hour/resources/v1/image-to-video";
import { LipSyncClient } from "magic-hour/resources/v1/lip-sync";
import { TextToVideoClient } from "magic-hour/resources/v1/text-to-video";
import { VideoProjectsClient } from "magic-hour/resources/v1/video-projects";
import { VideoToVideoClient } from "magic-hour/resources/v1/video-to-video";

export class V1Client extends CoreResourceClient {
  imageProjects: ImageProjectsClient;
  videoProjects: VideoProjectsClient;
  aiImageGenerator: AiImageGeneratorClient;
  faceSwap: FaceSwapClient;
  faceSwapPhoto: FaceSwapPhotoClient;
  files: FilesClient;
  imageToVideo: ImageToVideoClient;
  lipSync: LipSyncClient;
  textToVideo: TextToVideoClient;
  videoToVideo: VideoToVideoClient;

  constructor(client: CoreClient) {
    super(client);

    this.imageProjects = new ImageProjectsClient(this._client);
    this.videoProjects = new VideoProjectsClient(this._client);
    this.aiImageGenerator = new AiImageGeneratorClient(this._client);
    this.faceSwap = new FaceSwapClient(this._client);
    this.faceSwapPhoto = new FaceSwapPhotoClient(this._client);
    this.files = new FilesClient(this._client);
    this.imageToVideo = new ImageToVideoClient(this._client);
    this.lipSync = new LipSyncClient(this._client);
    this.textToVideo = new TextToVideoClient(this._client);
    this.videoToVideo = new VideoToVideoClient(this._client);
  }
}
